/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import model.Project;

public class App {
    // TODO code application logic here

    public static void main(String[] args) {

        /*ProjectController projectController = new ProjectController();

        Project project = new Project();

        project.setName("Projeto teste");
        project.setDescription("description");
        projectController.save(project);*/
    }
}
